sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_32807b1963c9_key -iv $encrypted_32807b1963c9_iv -in multi-k8s-238305-0883afd81cfe.json.enc -out multi-k8s-238305-0883afd81cfe.json -d
  - curl https://sdk.cloud.google.com | bash >/dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-238305
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # note: react-test is a temporary tag
  - docker build -t rhtakealot/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rhtakealot/react-test npm run test -- --coverage
